# Generated by Django 5.0.7 on 2024-08-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=100, unique=True)),
                ('ticker_symbol', models.CharField(max_length=100, unique=True)),
                ('ticker_sector', models.CharField(max_length=20)),
                ('ticker_market_cap', models.CharField(max_length=20)),
            ],
        ),
    ]
