# Generated by Django 5.1 on 2024-08-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannerpro', '0003_remove_tickerbase_ticker_market_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerbase',
            old_name='ticker_market_size',
            new_name='ticker_market_cap',
        ),
    ]
