# Generated by Django 5.1 on 2024-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerpro', '0004_rename_ticker_market_size_tickerbase_ticker_market_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tickerbase',
            name='ticker_market_cap',
            field=models.CharField(choices=[('Large Cap', 'Large Cap'), ('Mid Cap', 'Mid Cap'), ('Small Cap', 'Small Cap')], default='Large Cap', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickerbase',
            name='ticker_sector',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Banking', 'Banking'), ('Capital Goods', 'Capital Goods'), ('Cement', 'Cement'), ('Chemicals', 'Chemicals'), ('Finance', 'Finance'), ('FMCG', 'FMCG'), ('Index', 'Index'), ('Infrastructure', 'Infrastructure'), ('Media', 'Media'), ('Metals', 'Metals'), ('Oil and Gas', 'Oil and Gas'), ('Pharma', 'Pharma'), ('Power', 'Power'), ('Realty', 'Realty'), ('Technology', 'Technology'), ('Telecom', 'Telecom'), ('Textile', 'Textile'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
