# Generated by Django 5.1 on 2024-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerpro', '0005_accesstoken_alter_tickerbase_ticker_market_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='value',
            field=models.TextField(),
        ),
    ]
